### ISSUE TITLE
training and testing code release

### ISSUE THREAD

**Issue by lerndeep** [FelixHertlein/illtrtemplate-model#1]
Hello

waiting your training and testing code .
 could you please let me know when you are going to release?

Thank you

**Comment by FelixHertlein** [comment]
I am working on the release. 
It will be finished next week.

**Comment by lerndeep** [comment]
I am waiting for your code to train on my custom dataset. 
After you release the code I will train on my custom dataset and let you know the results.
thank you.

**Comment by FelixHertlein** [comment]
All code & data is now online!
