### ISSUE TITLE
how to make template.png?

### ISSUE THREAD

**Issue by qiuyuzhao** [FelixHertlein/illtrtemplate-model#3]
# prepare template
        if "template" in model_name:
            template_path = image_path.parent / "template.png"

            template = load_image(template_path)
            template = rearrange(template, "h w c -> () c h w")
            template = template.astype("float32") / 255
            template = torch.from_numpy(template)
            template = template.to("cuda")
it must enter template.png in the illtr_template@inv3d@pad=0 model, how to make template.png?

**Comment by FelixHertlein** [comment]
The invoice template image is part of the Inv3D dataset. You can download it from there.

If you have your own data, you need to make your own template image from a scan or the original word document.
